# Validate that generated files match OpenAPI spec
# Run this locally before pushing

Write-Host "=== ATLAS Contract Validation ===" -ForegroundColor Cyan

# Step 1: Regenerate artifacts
Write-Host "`n[1/4] Regenerating artifacts..." -ForegroundColor Yellow
dotnet build src/ATLAS.API/ATLAS.Api.csproj --verbosity quiet

if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: Build failed!" -ForegroundColor Red
    exit 1
}

# Step 2: Check for differences
Write-Host "`n[2/4] Checking generated files..." -ForegroundColor Yellow

$gitDiff = git diff --name-only src/ATLAS.API/Controllers/Generated/ src/ATLAS.API/Contracts/Generated/

if ($gitDiff) {
    Write-Host "`nERROR: Generated files are outdated!" -ForegroundColor Red
    Write-Host "Run: dotnet build src/ATLAS.API/ATLAS.Api.csproj" -ForegroundColor Yellow
    Write-Host "`nOutdated files:" -ForegroundColor Yellow
    $gitDiff | ForEach-Object { Write-Host "  $_" -ForegroundColor Yellow }
    exit 1
}

# Step 3: Validate OpenAPI spec (if tool available)
Write-Host "`n[3/4] Validating OpenAPI spec..." -ForegroundColor Yellow

# Check if hidi is available (locally installed via dotnet-tools.json)
$hidiAvailable = dotnet tool list | Select-String "microsoft.openapi.hidi"

if ($hidiAvailable) {
    Write-Host "Found hidi tool. Validating..." -ForegroundColor Green
    dotnet tool run hidi validate -d openapi/atlas-api.yaml
    if ($LASTEXITCODE -ne 0) {
        Write-Host "WARNING: OpenAPI spec validation failed!" -ForegroundColor Yellow
    } else {
        Write-Host "✅ OpenAPI spec is valid!" -ForegroundColor Green
    }
} else {
    Write-Host "WARNING: 'hidi' tool not installed locally." -ForegroundColor Yellow
    Write-Host "Run: dotnet tool restore" -ForegroundColor Yellow
    Write-Host "Skipping validation..." -ForegroundColor Yellow
}

# Step 4: Check for manual edits to generated files
Write-Host "`n[4/5] Checking for manual edits..." -ForegroundColor Yellow

$generatedFiles = @(
    "src/ATLAS.API/Controllers/Generated/GeneratedControllers.g.cs",
    "src/ATLAS.API/Contracts/Generated/AtlasContracts.g.cs"
)

foreach ($file in $generatedFiles) {
    $content = Get-Content $file -Raw
    if ($content -match "// <auto-generated>" -or $content -match "// <auto-generated>") {
        # Good - file has auto-generated comment
    } else {
        Write-Host "WARNING: $file may have been manually edited!" -ForegroundColor Yellow
    }
}

# Step 5: Detect breaking changes (compare with origin/main)
Write-Host "`n[5/5] Checking for breaking changes..." -ForegroundColor Yellow

# Try to get main spec from origin/main (fetch first)
git fetch origin main 2>$null
$mainSpec = git show origin/main:openapi/atlas-api.yaml 2>$null

if ($LASTEXITCODE -eq 0) {
    # Save main spec to temp file
    $tempFile = [System.IO.Path]::GetTempFileName()
    $mainSpec | Out-File -FilePath $tempFile -Encoding UTF8
    
    # Run openapi-compare
    $compareTool = Get-Command "openapi-compare" -ErrorAction SilentlyContinue
    
    if ($compareTool) {
        $diffOutput = openapi-compare -o $tempFile -n openapi/atlas-api.yaml -f Text 2>&1
        if ($diffOutput -match "Breaking") {
            Write-Host "⚠️ Breaking changes detected!" -ForegroundColor Red
            Write-Host $diffOutput -ForegroundColor Yellow
            Write-Host "Consider bumping major version (x.0.0)" -ForegroundColor Yellow
        } else {
            Write-Host "✅ No breaking changes detected" -ForegroundColor Green
        }
    } else {
        Write-Host "WARNING: 'openapi-compare' not found." -ForegroundColor Yellow
        Write-Host "Install: dotnet tool restore" -ForegroundColor Yellow
    }
    
    # Cleanup
    Remove-Item $tempFile -Force -ErrorAction SilentlyContinue
} else {
    Write-Host "WARNING: Cannot fetch origin/main. Skipping breaking change detection." -ForegroundColor Yellow
    Write-Host "Ensure you have access to the remote repository." -ForegroundColor Yellow
}

Write-Host "`n✅ Contract validation passed!" -ForegroundColor Green
Write-Host "Generated files are up-to-date with openapi/atlas-api.yaml" -ForegroundColor Green
